### ISSUE TITLE
flux_open(shmem://...) now requires a zeromq context

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-pmix#89]
Problem: A recent change to flux-core broke flux-pmix.  I had forgotten that back to back flux `shmem://` handles are used to communicate between the pmix service thread callbacks and the shell main thread, and this now requires a zeromq context.

**Comment by grondo** [comment]
Do we need to add a flux-pmix test build to flux-core CI, esp if this will be the suggested way to run all OpenMPI jobs going forward.

**Comment by garlick** [comment]
Definitely something to consider.  Would have helped here!
