### ISSUE TITLE
Full name needed for release

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-pmix#97]
Could we rename the release from today to have flux-pmix too? It's used to derive the docs site, and it's missing flux-pmix:

![image](https://github.com/flux-framework/flux-pmix/assets/814322/e89764e2-d55f-4c89-aad9-8f1f573c06ff)

here: https://flux-framework.org/releases/

I'll manually fix that page for now, but would be good to fix here too. Thank you!

**Comment by vsoch** [comment]
Fixed there! https://github.com/flux-framework/flux-framework.github.io/commit/17058875805c97277ddac7c501677ba122677e3b

**Comment by garlick** [comment]
Whoops!  Fixed!

**Comment by vsoch** [comment]
Thank you!
